HW1
================
Yi Sun

Solution to HW1.

# Problem 1

Create a data frame comprised of specified elements.

``` r
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_leng_10 = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_3_lvl = factor(c("high", "high", "high", "high", "mod", "mod", "mod", "low", "low", "low"))
)
```

Try to take the mean of each variable in the data frame.

``` r
mean(pull(prob1_df, samp))
```

    ## [1] -0.09515283

``` r
mean(pull(prob1_df, samp_gt_0))
```

    ## [1] 0.7

``` r
mean(pull(prob1_df, char_leng_10))
```

    ## Warning in mean.default(pull(prob1_df, char_leng_10)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_3_lvl))
```

    ## Warning in mean.default(pull(prob1_df, factor_3_lvl)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

I can only take the mean of numeric or logical variables but not
character or factor variables.

Try to convert the logical variable `samp_gt_0`, character variable
`char_leng_10`, and factor variable `factor_3_lvl` into numeric
variables.

``` r
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_leng_10))
as.numeric(pull(prob1_df, factor_3_lvl))
```

The logical variable `samp_gt_0` and factor variable `factor_3_lvl` are
converted into numeric variables, but I cannot convert the character
variable `char_leng_10` into a numeric variable (returning NAs). I think
it’s because there are characters included in the string values of
`char_leng_10` (i.e., string values like “111”, “222”, “333” of a
character variable can be converted into numeric values).

This may help explain why I can only take the mean of numeric or logical
variables: values of factor variables are not numbers before factor
variables are converted into numeric variables, and values of logical
variables are interpreted as 1 for TRUE and 0 for FALSE when I take the
mean. String values of character variables including characters are not
numbers and even cannot be converted into numeric values.

Try to multiply the numeric variable `samp` by the results of different
conversions on the logical variable `samp_gt_0`.

``` r
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ##  [1] 0.0000000 0.8661633 0.5113095 0.2834868 0.4566616 0.0000000 0.1324984
    ##  [8] 0.0819900 0.7035976 0.0000000

``` r
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_gt_0)), pull(prob1_df, : '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```

    ##  [1] -1.6276456  1.7323266  1.0226191  0.5669737  0.9133233 -0.7126484
    ##  [7]  0.2649967  0.1639800  1.4071952 -1.6469416

`as.factor` function can convert logical variables into factor
variables, but the result of conversion cannot directly multiply numeric
variables. I can only multiply numeric variables by numeric variables.

# Problem 2

The summary of the `penguins` dataset is as below:

``` r
data("penguins", package = "palmerpenguins")
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

Variables in this dataset include: species, island, bill\_length\_mm,
bill\_depth\_mm, flipper\_length\_mm, body\_mass\_g, sex, year.

The factor variable `species` has 3 levels: Adelie, Chinstrap, Gentoo.

The factor variable `island` has 3 levels: Biscoe, Dream, Torgersen.

The numeric variable `bill_length_mm`’s range is (32.1, 59.6), and its
mean is 43.9219298.

The integer variable `flipper_length_mm`’s range is (172, 231), and its
median is 197.

This dataset has 344 rows and 8 columns.

The mean flipper length is 200.9152047 mm.

Make a scatterplot of `flipper_length_mm` (y) vs `bill_length_mm` (x)
and color points using the `species` variable.

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_ys3297_files/figure-gfm/prob2_scatterplot-1.png)<!-- -->

``` r
ggsave(file = "hw1_prob2_scatterplot.png")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

The scatterplot is saved as “hw1\_prob2\_scatterplot.png”.
